### ISSUE TITLE
Canvas Público

### ISSUE THREAD

**Issue by Matheusg2002** [ifgamessc/Folclore#33]

**Comment by Matheusg2002** [comment]
https://store.steampowered.com/app/1179080/FAITH_The_Unholy_Trinity/

**Comment by boidacarapreta** [comment]
Encontrei o arquivo (PDF) no repositório. Pode ignorar a [mensagem anterior](https://github.com/ifgamessc/Folclore/issues/33#issuecomment-1522209090).
